post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZWtzYW5kYXIiLCJpZCI6IjYxOTNjOTM3OGIzYjM3NWEwYmVkZTQ2MyIsImlhdCI6MTYzNzA3OTIxNH0.jVg1W5O_NsAK-K66joPuEOvBBmBCm-E0WvXAMogDcv4

{
    "title": "Only logged in users can see this",
    "url":"http",
    "author": "Aleksandar"
}